backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

site_url: https://blog.crisp.studio
media_folder: static/assets
public_folder: assets

collections:
  - name: post
    label: Post
    folder: src/content/posts
    preview_path: /{{slug}}
    create: true
    fields:
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - {
          name: tags,
          label: Tags,
          widget: select,
          multiple: true,
          options: [updates, interviews, design, development],
        }
      - {
          name: author,
          label: Author,
          widget: select,
          options: [Daniel Wirtz, René Nauheimer, Leo Bernard],
        }
      - { name: image, label: Header Image, widget: image }
      - { name: body, label: Body, widget: markdown }
